### ISSUE TITLE
Move to iojs org?

### ISSUE THREAD

**Issue by bnoordhuis** [iojs/nan#266]
See iojs/io.js#544 for background.

I think we want to encourage people to switch to nan.  Moving it to https://github.com/iojs gives off a clear signal that it's the blessed approach.  Thoughts?

/cc @kkoopa @rvagg

**Comment by kkoopa** [comment]
Sure, that makes sense in a way. But should iojs/io.js then bundle a suitable version of nan? Can we still release  new versions independently?

**Comment by XadillaX** [comment]
Congratulations!

**Comment by jonathanong** [comment]
:+1:

**Comment by Qard** [comment]
I agree with blessing nan, but I'm not sure it'd be a good idea for it to be bundled with io.js itself.

One might draw parallels to npm being a separate thing that gets bundled with it. But development of npm moves forward in terms of support, while nan effectively moves backward from each version.

The API surface that native modules have to interact with may change over time to support the same past version due to subtle differences introduced in newer versions.

**Comment by bnoordhuis** [comment]
> But should iojs/io.js then bundle a suitable version of nan?

I don't think so.  nan would remain an independent project, evolving at its own pace.  It would be living under the iojs umbrella mainly for messaging reasons (and perhaps better visibility and easier coordination, although that's working pretty well already.)

**Comment by kkoopa** [comment]
How to proceed?

**Comment by bnoordhuis** [comment]
I think @rvagg has to initiate the move.

**Comment by rvagg** [comment]
Yeah, been stalling on this to see how the other working groups evolve. TBH, and I know this probably seems silly to some, my biggest beef has been the strong adoption of "codes of conduct" which I don't believe belong in this arena (IMO they are useless at best and toxic at their worst, save them for conferences) and I don't really want to see that forced upon this project.

I think I would interpret the current wording *"The WG is free to change these documents through their own governance process,"* as meaning they can be ditched if desired. I'm just one voice on that anyway and perhaps you all love these things.

Can I get a +1 from active collaborators please?

* @bnoordhuis (assumed from this thread)
* @kkoopa (assumed from this thread)
* @brett19 
* @agnat

Please review https://github.com/iojs/io.js/blob/v1.x/WORKING_GROUPS.md to see if it's something you can agree to.

**Comment by agnat** [comment]
+1

**Comment by kkoopa** [comment]
I agree with Rod on the code of conduct. I assumed the io.js code of conduct applies to io.js only. The working groups document states that "The WG has final authority over this project including: [...] Conduct guidelines", so that should mean we don't have to adopt them.

I don't, however, care too much for the weekly meeting point. It's worked fine without weekly meetings for the past two years. Enough of us are in meetings already.

**Comment by rvagg** [comment]
agreed on the meetings, we've got a pretty good github workflow going on here

**Comment by bnoordhuis** [comment]
+1 and agreed we can do without the CoC and weekly meetings.

**Comment by brett19** [comment]
+1

**Comment by Pana** [comment]
+1

**Comment by KenanSulayman** [comment]
Looks like everyone is OK with it. What's keeps this from moving?

**Comment by rvagg** [comment]
Just had a thought because the io.js Spanish team want to translate my https://github.com/rvagg/node-addon-examples repo--we should just pull that project in with NAN and manage them together as the NAN team, let me know if there are any objections to that but this'd be a perfect role to extend what we're doing here.

**Comment by KenanSulayman** [comment]
I think the examples should be merged with nan and be updated alongside any changes to nan. On top of that, nan should be elevated to be a part of the io.js organisation (*and eventually be shipped with io.js*).

**Comment by JCMais** [comment]
> Spanish team want to translate 

I'm curious here, any info about it? What if someone else wants to do the same, but to another language?

**Comment by rvagg** [comment]
@JCMais https://github.com/iojs/iojs-es/issues/78 is the original issue

You should consider joining an io.js language team if you have translation skills. Respond here: https://github.com/iojs/website/issues/125

**Comment by rvagg** [comment]
welcome to iojs/nan and the @iojs/addon-api team folks. @kkoopa, @brett19 and @agnat you should all have invites to join the org, let me know if you have any trouble with it.
