### ISSUE TITLE
NanMakeWeakPersistent for existing Persistent

### ISSUE THREAD

**Issue by jka6502** [iojs/nan#283]
I find my most common use case for `NanMakeWeakPersistent` ends up requiring retention of a (possible) reference to an object, while not inhibiting the garbage collector's ability to dispose of that object if no references remain on the JS side, but this use case is currently impossible via nan, as `NanMakeWeakPersistent` can not return the `Persistent` created (without some copyable traits shenanigans), nor allow the developer to make an existing `Persistent` weak - and I'd rather not mix nan and raw v8 api calls for the same mechanism, if possible.

To me, it would make sense if there were an alternative function, that modified an existing `Persistent`, so that there is an option to:

```C++
NanAssignPersistent(myPersistentReference, someHandle);
NanMakeWeak(myPersistentReference, param, &callback);
```

(Suggested naming is purely an example, mind you - as the existing function kinda steps on the obvious choice :-P)

**Comment by kkoopa** [comment]
It would indeed be nicer that way, but unfortunately it is not possible. Currently I do not remember why, but I initially tried making it that way, since it is the natural way of doing things.

Still, all hope is not lost. `NanMakeWeakPersistent` does in fact return a `_NanWeakCallbackInfo<T, P> *`, which in turn contains the `Persistent` handle in its `persistent` member.
```c++
_NanWeakCallbackInfo<Object, void*>* weak = NanMakeWeakPersistent(...);
weak->persistent.Reset();
```
Do note that it is possible to shoot yourself in the foot in many ways with this returned object, so its use is discouraged. If at all possible, you are better off changing the surrounding code instead. The `_NanWeakCallbackInfo` struct is intended as internal, but was exposed (yet undocumented) for this very reason.

**Comment by jamesatfanduel** [comment]
Thank you for the quick response, and explanation, and damn - that is going to make things awkward for me.

I'm using a `std::map` of native C++ instances to `Isolate` specific `Object`s (basically a multi-thread safe/capable alternative to `node::ObjectWrap`, to expose and manage a single C++ instance in multiple contexts).  My *simple* solution is to implement a base class for wrappable C++ objects, which contains a hidden `map<Isolate*, Persistent<Object> >`, and then make each entry weak - so that the class can identify when no `Isolate`s still have a reference to the wrapped instance.

This only really applies to node 0.12 at the moment, though I'd still rather use nan to allow more graceful handling of future node/v8 versions.

I can't find any information about whether 'weakness' is transferred via `CopyablePersistentTraits`, though I very much doubt it, so I'll have to resort to either a) pointers to `Persistent` instances in my map, pointing to the objects Nan creates (which has a bad smell to me), or b) not use nan for disposal handling in those particular maps (which is a little defeatist!).

**Comment by jka6502** [comment]
Thank you for the quick response, and explanation, and damn - that is going to make things awkward for me.

I'm using a `std::map` of native C++ instances to `Isolate` specific `Object`s (basically a multi-thread safe/capable alternative to `node::ObjectWrap`, to expose and manage a single C++ instance in multiple contexts).  My *simple* solution is to implement a base class for wrappable C++ objects, which contains a hidden `map<Isolate*, Persistent<Object> >`, and then make each entry weak - so that the class can identify when no `Isolate`s still have a reference to the wrapped instance.

This only really applies to node 0.12 at the moment, though I'd still rather use nan to allow more graceful handling of future node/v8 versions.

I can't find any information about whether 'weakness' is transferred via `CopyablePersistentTraits`, though I very much doubt it, so I'll have to resort to either a) pointers to `Persistent` instances in my map, pointing to the objects Nan creates (which has a bad smell to me), or b) not use nan for disposal handling in those particular maps (which is a little defeatist!).

**Comment by kkoopa** [comment]
If you want them weak, it seems like you have to make it a `map<Isolate*, _NanWeakCallbackInfo<Object,P>*>`.

If I remember correctly, the reason why the `Persistent` has to be in that structure is because it is needed in the callback, so it has to be supplied there somehow. Combined with `Persistent` being non-assignable you end up with this mess. You can probably not even circumvent it by rolling your own, as you need access to that original `Persistent` in the callback. What you'll end up with is something similar to `_NanWeakCallbackInfo`.
